/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentsystem;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Kurea
 */
public class loginPage extends javax.swing.JFrame {

    private static final String url = "jdbc:mysql://localhost:3306/enrollmentsys";
    
    Connection connDB1 = null;
    Connection connDB2 = null;
    Connection connDB3 = null;
    
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form loginPage
     */
    public loginPage() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TFStdID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        RegButton = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 52)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BENKYOU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 221, 30));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enrollment System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 290, 38));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        jPanel2.setBackground(new java.awt.Color(138, 6, 6));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 70, -1));

        TFStdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFStdIDActionPerformed(evt);
            }
        });
        jPanel3.add(TFStdID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 420, 40));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Password");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 120, -1));

        jButton1.setBackground(new java.awt.Color(51, 102, 0));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 100, 40));

        RegButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        RegButton.setForeground(new java.awt.Color(185, 8, 8));
        RegButton.setText("Haven't registered yet? Register");
        RegButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegButtonMouseClicked(evt);
            }
        });
        jPanel3.add(RegButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel3.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 420, 40));

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Faculty", "Admin" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 150, 30));

        jCheckBox1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 15)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 620, 310));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BSAIS 2-1, All Rights Reserved.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGIN");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 130, 38));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // login button
        try
        {
            String username = TFStdID.getText();
            String password = String.valueOf(jPasswordField1.getPassword());
            
            String selectedUserType = (String) jComboBox1.getSelectedItem();
            switch (selectedUserType) {
                case "Student":
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    connDB2 = DriverManager.getConnection(url, "root", "$4Y my n4m3");
                    pst = connDB2.prepareStatement("SELECT * FROM `enrollmentsys`.`logindatastudent` WHERE `StudentID` = ? and `Password` = ?");
                    pst.setString(1, username);
                    pst.setString(2, password);
                    rs = pst.executeQuery();
                    
                    if (rs.next())
                    {
                        String name = rs.getString("Name");
                        JOptionPane.showMessageDialog(null, "Login successful.");
                        new StudentFrame(name).setVisible(true);
                        dispose(); // Close the current loginPage frame
                    }else{
                        if (username.isEmpty() && password.isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please fill in all fields", "Error",JOptionPane.ERROR_MESSAGE);
                        }else if(password.equals("")){
                        JOptionPane.showMessageDialog(null, "Password is empty.", "Error",JOptionPane.ERROR_MESSAGE);
                        }else if (username.equals("")){
                        JOptionPane.showMessageDialog(null, "Username is empty.", "Error",JOptionPane.ERROR_MESSAGE);
                        }else{
                        JOptionPane.showMessageDialog(null, "Incorrect details. Please try again","Error",  JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    break;
                    
                case "Faculty":
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    connDB3 = DriverManager.getConnection(url, "root", "$4Y my n4m3");
                    pst = connDB3.prepareStatement("SELECT * FROM `enrollmentsys`.`logindatafaculty` WHERE `FacultyID` = ? and `Password` = ?");
                    
                    pst.setString(1, username);
                    pst.setString(2, password);
                    rs = pst.executeQuery();
                    if (rs.next())
                    {
                        String name = rs.getString("Name");
                        JOptionPane.showMessageDialog(null, "Login successful.");
                        new FacultyFrame(name).setVisible(true);
                        dispose(); // Close the current loginPage frame
                    }
                    else
                    {
                        if (username.isEmpty() && password.isEmpty()){
                            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Error",JOptionPane.ERROR_MESSAGE);
                        }else if(password.equals("")){
                            JOptionPane.showMessageDialog(null, "Password is empty.", "Error",JOptionPane.ERROR_MESSAGE);
                        }else if (username.equals("")){
                            JOptionPane.showMessageDialog(null, "Username is empty.", "Error",JOptionPane.ERROR_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(null, "Incorrect details. Please try again","Error",  JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    break;
                    
                case "Admin":
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    connDB1 = DriverManager.getConnection(url, "root", "$4Y my n4m3");
                    pst = connDB1.prepareStatement("SELECT * FROM `enrollmentsys`.`login_admin` WHERE `Email` = ? and `Password` = ?");
                    
                    pst.setString(1, username);
                    pst.setString(2, password);
                    rs = pst.executeQuery();
                    if (rs.next())
                    {
                        JOptionPane.showMessageDialog(null, "Login successful.");
                        new AdminFrame().setVisible(true);
                        dispose(); // Close the current loginPage frame
                    }else{
                        if (username.isEmpty() && password.isEmpty()){
                        JOptionPane.showMessageDialog(null, "Please fill in all fields", "Error",JOptionPane.ERROR_MESSAGE);
                        }else if(password.equals("")){
                        JOptionPane.showMessageDialog(null, "Password is empty.", "Error",JOptionPane.ERROR_MESSAGE);
                        }else if (username.equals("")){
                        JOptionPane.showMessageDialog(null, "Username is empty.", "Error",JOptionPane.ERROR_MESSAGE);
                        }else{
                        JOptionPane.showMessageDialog(null, "Incorrect details. Please try again","Error",  JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    break;
                    
                default:
                    
                    break;
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegButtonMouseClicked
        // TODO add your handling code here:
        
        // register page
        new Register().setVisible(true);
        dispose();
    }//GEN-LAST:event_RegButtonMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        // type of login'
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if
        (jCheckBox1.isSelected()){

            jPasswordField1.setEchoChar((char)0);
        }
        else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void TFStdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFStdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFStdIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RegButton;
    private javax.swing.JTextField TFStdID;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
